### ISSUE TITLE
Features, docs and funding???

### ISSUE THREAD

**Issue by foozzi** [ksenginew/fullmoon#5]
hi @ksenginew
what features are implemented at the moment? 

will there be documentation? 

dude create a patreon so people like us can fund the fork

**Comment by ksenginew** [comment]
Hi @foozzi ,

Currently fullmoon is a copy of halfmoon. but converted to sass and code splitted. So [halfmoon docs](https://www.gethalfmoon.com/docs/containers/) is mostly valid.

Next version of fullmoon is currently in development. It's a fork of bootstrap with the features of fullmoon.
- tons of css variables to customize it
- dark mode(not yet)

So [Bootstrap docs](https://getbootstrap.com/docs) is mostly valid for that version. But I hope to create new docs with references to bootstrap docs.

But It needs more work. [develop branch](https://github.com/ksenginew/fullmoon/tree/develop) contains my work for new version.

There is a sponsor button(only desktop) and sponsor section in [front page](https://github.com/ksenginew/fullmoon).

Thanks for your encouragement 🙂. Please help this project grow.
